symlinks:
  - src: ..\av3-animator-as-code
    dest: ..\..\Packages\jp.suzuryg.face-emo\Ext\AnimatorAsCodeFramework
    target:
      - LICENSE
    include-meta-file: false
  - src: ..\av3-animator-as-code\Framework\Editor\V0
    dest: ..\..\Packages\jp.suzuryg.face-emo\Ext\AnimatorAsCodeFramework
    target:
      - Aac.cs
      - AacAnimatorNode.cs
      - AacDefaultsProvider.cs
      - AacFlAnimations.cs
      - AacFlConditions.cs
      - AacFlStates.cs
    include-meta-file: false
  - src: ..\av3-animator-as-code\Framework\Editor\V0\Extensions\VRChat
    dest: ..\..\Packages\jp.suzuryg.face-emo\Ext\AnimatorAsCodeFramework
    target:
      - TrackingElement.cs
      - VRChatExtensions.cs
    include-meta-file: false

  - src: ..\combo-gesture-expressions-av3\Assets\Hai\ComboGesture\Scripts\Editor\Internal
    dest: ..\..\Packages\jp.suzuryg.face-emo\Ext\ComboGestureIntegrator\Internal
    target:
      - CgeAssetContainer.cs
      - CgeLayerForAnalogFistSmoothing.cs
      - CgeLayerForWeightCorrection.cs
    include-meta-file: false

  - src: ..\combo-gesture-expressions-av3\Assets\Hai\ComboGesture\Scripts\Editor\Internal\CgeAac
    dest: ..\..\Packages\jp.suzuryg.face-emo\Ext\ComboGestureIntegrator\Internal
    target:
      - CgeAac.cs
      - CgeAacAnimatorNode.cs
      - CgeAacDefaultsProvider.cs
      - CgeAacFlAnimations.cs
      - CgeAacFlConditions.cs
      - CgeAacFlStates.cs
      - CgeAac_LICENSE
    include-meta-file: false
