symlinks:
  - src: ..\av3-animator-as-code
    dest: ..\..\Packages\jp.suzuryg.facial-expression-switcher\External\Hai\AnimatorAsCodeFramework
    target:
      - LICENSE
    include-meta-file: false
  - src: ..\av3-animator-as-code\Framework\Editor\V0
    dest: ..\..\Packages\jp.suzuryg.facial-expression-switcher\External\Hai\AnimatorAsCodeFramework
    target:
      - Aac.cs
      - AacAnimatorNode.cs
      - AacDefaultsProvider.cs
      - AacFlAnimations.cs
      - AacFlConditions.cs
      - AacFlStates.cs
    include-meta-file: false
  - src: ..\av3-animator-as-code\Framework\Editor\V0\Extensions\VRChat
    dest: ..\..\Packages\jp.suzuryg.facial-expression-switcher\External\Hai\AnimatorAsCodeFramework
    target:
      - TrackingElement.cs
      - VRChatExtensions.cs
    include-meta-file: false

  - src: ..\blendshape-viewer
    dest: ..\..\Packages\jp.suzuryg.facial-expression-switcher\External\Hai\VisualExpressionsEditor
    target:
      - LICENSE
    include-meta-file: false
  - src: ..\blendshape-viewer\Assets\Hai
    dest: ..\..\Packages\jp.suzuryg.facial-expression-switcher\External\Hai\VisualExpressionsEditor
    target:
      - VisualExpressionsEditor
    include-meta-file: true

  - src: ..\combo-gesture-expressions-av3\Assets\Hai\ComboGesture\Scripts\Editor\Internal
    dest: ..\..\Packages\jp.suzuryg.facial-expression-switcher\External\Hai\ComboGestureIntegrator\Internal
    target:
      - CgeAssetContainer.cs
      - CgeLayerForAnalogFistSmoothing.cs
      - CgeLayerForWeightCorrection.cs
    include-meta-file: false

  - src: ..\combo-gesture-expressions-av3\Assets\Hai\ComboGesture\Scripts\Editor\Internal\CgeAac
    dest: ..\..\Packages\jp.suzuryg.facial-expression-switcher\External\Hai\ComboGestureIntegrator\Internal
    target:
      - CgeAac.cs
      - CgeAacAnimatorNode.cs
      - CgeAacDefaultsProvider.cs
      - CgeAacFlAnimations.cs
      - CgeAacFlConditions.cs
      - CgeAacFlStates.cs
      - CgeAac_LICENSE
    include-meta-file: false

  - src: ..\Extenject\UnityProject\Assets\Plugins
    dest: ..\..\Packages\jp.suzuryg.facial-expression-switcher\External\Mathijs-Bakker
    target:
      - Zenject
    include-meta-file: true

  - src: ..\UniRx
    dest: ..\..\Packages\jp.suzuryg.facial-expression-switcher\External\neuecc\UniRx
    target:
      - LICENSE
    include-meta-file: false
  - src: ..\UniRx\Assets\Plugins\UniRx
    dest: ..\..\Packages\jp.suzuryg.facial-expression-switcher\External\neuecc\UniRx
    target:
      - Scripts
    include-meta-file: true
